version: '3'
services:
  frontend-test:
    image: appdev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","test"]