version: 2
jobs:
  build:
    docker:
      - image: docker:20.10.15-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/docker_layers.tar
      - run:
          name: load docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/frontend.tar | true
      - run:
          name: use pulled image to build cache
          command: |
            pwd
            docker build -t frontend-in-docker .
