# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  frontend:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: echo "install and test"
      - run: cd frontend; npm install; npm test

workflows:
  sample:
    jobs:
      - frontend
